menu:
  enabled: true

  title: "&6&lEG &7➜ &eSettings"
  size: 54

  fill: true

  items:

    members:
      slot: 13
      material: "HEAD: %player%"
      name: "&6Members"
      lore:
        - ""
        - " &8▪ &7Member Amount&8: &e%generator_member_amount%"
        - ""
        - " &8&l→ &eClick to member settings!"
        - ""

    autoBreak:
      slot: 30
      material: "DIAMOND_PICKAXE"
      name: "&6Auto Break"
      lore:
        - ""
        - " &8▪ &7Buyed&8: &e%generator_auto_break_buyed%"
        - " &8▪ &7Enabled&8: &e%generator_auto_break_enabled%"
        - ""
        - " &8&l→ &eClick to enable!"
        - ""

    autoPickup:
      slot: 31
      material: "HOPPER"
      name: "&6Auto Pickup"
      lore:
        - ""
        - " &8▪ &7Buyed&8: &e%generator_auto_pickup_buyed%"
        - " &8▪ &7Enabled&8: &e%generator_auto_pickup_enabled%"
        - ""
        - " &8&l→ &eClick to enable!"
        - ""

    autoSmelt:
      slot: 32
      material: "FURNACE"
      name: "&6Auto Smelt"
      lore:
        - ""
        - " &8▪ &7Buyed&8: &e%generator_auto_smelt_buyed%"
        - " &8▪ &7Enabled&8: &e%generator_auto_smelt_enabled%"
        - ""
        - " &8&l→ &eClick to enable!"
        - ""

    autoChest:
      slot: 39
      material: "CHEST"
      name: "&6Auto Chest"
      lore:
        - ""
        - " &8▪ &7Buyed&8: &e%generator_auto_chest_buyed%"
        - " &8▪ &7Enabled&8: &e%generator_auto_chest_enabled%"
        - ""
        - " &8&l→ &eClick to enable!"
        - ""

    hologram:
      slot: 40
      material: "SIGN"
      name: "&6Generator's Hologram"
      lore:
        - ""
        - " &8▪ &7Enabled&8: &e%generator_hologram_enabled%"
        - ""
        - " &8&l→ &eClick to enable!"
        - ""

    delete:
      slot: 41
      material: "BARRIER"
      name: "&6Delete Generator"
      lore:
        - ""
        - "&7&o(if you delete the generator,"
        - " &7&oyou will be given the generator item.)"
        - ""
        - " &8&l→ &eClick to delete generator!"
        - ""

    close:
      slot: 36
      material: "ARROW"
      name: "&6Back"
      lore:
        - ""
        - " &8&l→ &eBack to previous"
        - ""
